[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"

# --- 1. ENTRADA: MOSQUITTO (MQTT) ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  # Suscribirse a todos los tópicos de métricas de la mesh
  topics = [
    "iot/mesh/node/+/metrics/#"
  ]

  # Forzamos que la medida (tabla) en InfluxDB se llame exactamente así
  name_override = "mqtt_consumer"


  data_format = "json"


  tag_keys = ["mac"]


[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "sensores"