agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"

# --- 1. ENTRADA: MOSQUITTO (MQTT) ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  # Suscribirse a todos los tópicos de métricas de la mesh
  topics = [
    "iot/mesh/node/+/metrics"
  ]

  # IMPORTANTE: Cambiamos a formato JSON
  data_format = "json"

  # Esto le dice a Telegraf que use la MAC como etiqueta para distinguir los nodos
  tag_keys = ["mac"]

# --- 2. SALIDA: INFLUXDB ---
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "sensores"
  # Si usas InfluxDB 1.8, deja esto así. Si usas 2.x necesitas el token.